server:
  port: 8080
  servlet:
    context-path: /
spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console

  jwt:
    secret: your-secret-key
    access-token:
      expire-length: 3600000

logging:
  file:
    name:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
